// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdHzyjClqIHA1aFfDI02qm7B7kOktj8jA',
    appId: '1:865148063189:web:10e4d1dc600c8f10b8015c',
    messagingSenderId: '865148063189',
    projectId: 'fruitshub-d0526',
    authDomain: 'fruitshub-d0526.firebaseapp.com',
    storageBucket: 'fruitshub-d0526.firebasestorage.app',
    measurementId: 'G-3Y0BYZCG1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM6-mngiJDAjvVltKCvp4lKGBeSzeMuFE',
    appId: '1:865148063189:android:32e05f8c2c5ae4afb8015c',
    messagingSenderId: '865148063189',
    projectId: 'fruitshub-d0526',
    storageBucket: 'fruitshub-d0526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcFoKWKymdOaRwWpugerE4Z3PTHzC0Pmk',
    appId: '1:865148063189:ios:7780770095891336b8015c',
    messagingSenderId: '865148063189',
    projectId: 'fruitshub-d0526',
    storageBucket: 'fruitshub-d0526.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcFoKWKymdOaRwWpugerE4Z3PTHzC0Pmk',
    appId: '1:865148063189:ios:7780770095891336b8015c',
    messagingSenderId: '865148063189',
    projectId: 'fruitshub-d0526',
    storageBucket: 'fruitshub-d0526.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdHzyjClqIHA1aFfDI02qm7B7kOktj8jA',
    appId: '1:865148063189:web:fa99c91ec28c2821b8015c',
    messagingSenderId: '865148063189',
    projectId: 'fruitshub-d0526',
    authDomain: 'fruitshub-d0526.firebaseapp.com',
    storageBucket: 'fruitshub-d0526.firebasestorage.app',
    measurementId: 'G-61H991L83K',
  );
}
